create table type (
	t_id  INTEGER PRIMARY KEY AUTO_INCREMENT,
	type VARCHAR(12),
	weight DECIMAL(2,1),
	sec_id INTEGER NOT NULL REFERENCES section
);


insert into type (t_id, type, weight, sec_id) values (1, 'project', 0.1, 202);
insert into type (t_id, type, weight, sec_id) values (2, 'homework', 0.0, 775);
insert into type (t_id, type, weight, sec_id) values (3, 'extra credit', 0.3, 520);
insert into type (t_id, type, weight, sec_id) values (4, 'extra credit', 0.5, 776);
insert into type (t_id, type, weight, sec_id) values (5, 'extra credit', 0.7, 908);
insert into type (t_id, type, weight, sec_id) values (6, 'project', 0.5, 794);
insert into type (t_id, type, weight, sec_id) values (7, 'test', 0.7, 602);
insert into type (t_id, type, weight, sec_id) values (8, 'extra credit', 0.1, 504);
insert into type (t_id, type, weight, sec_id) values (9, 'project', 0.7, 596);
insert into type (t_id, type, weight, sec_id) values (10, 'homework', 0.3, 150);
insert into type (t_id, type, weight, sec_id) values (11, 'extra credit', 0.4, 707);
insert into type (t_id, type, weight, sec_id) values (12, 'test', 0.6, 570);
insert into type (t_id, type, weight, sec_id) values (13, 'project', 0.1, 47);
insert into type (t_id, type, weight, sec_id) values (14, 'test', 0.8, 887);
insert into type (t_id, type, weight, sec_id) values (15, 'project', 0.6, 161);
insert into type (t_id, type, weight, sec_id) values (16, 'project', 0.9, 819);
insert into type (t_id, type, weight, sec_id) values (17, 'extra credit', 0.5, 748);
insert into type (t_id, type, weight, sec_id) values (18, 'homework', 0.5, 973);
insert into type (t_id, type, weight, sec_id) values (19, 'test', 0.7, 837);
insert into type (t_id, type, weight, sec_id) values (20, 'test', 0.1, 956);
insert into type (t_id, type, weight, sec_id) values (21, 'homework', 0.7, 168);
insert into type (t_id, type, weight, sec_id) values (22, 'test', 0.6, 804);
insert into type (t_id, type, weight, sec_id) values (23, 'extra credit', 0.9, 778);
insert into type (t_id, type, weight, sec_id) values (24, 'extra credit', 0.3, 789);
insert into type (t_id, type, weight, sec_id) values (25, 'extra credit', 1.0, 723);
insert into type (t_id, type, weight, sec_id) values (26, 'test', 0.3, 654);
insert into type (t_id, type, weight, sec_id) values (27, 'homework', 0.6, 273);
insert into type (t_id, type, weight, sec_id) values (28, 'test', 0.7, 434);
insert into type (t_id, type, weight, sec_id) values (29, 'test', 0.5, 52);
insert into type (t_id, type, weight, sec_id) values (30, 'project', 0.4, 754);
insert into type (t_id, type, weight, sec_id) values (31, 'project', 0.2, 956);
insert into type (t_id, type, weight, sec_id) values (32, 'homework', 0.6, 57);
insert into type (t_id, type, weight, sec_id) values (33, 'project', 0.2, 727);
insert into type (t_id, type, weight, sec_id) values (34, 'project', 0.2, 715);
insert into type (t_id, type, weight, sec_id) values (35, 'project', 0.9, 318);
insert into type (t_id, type, weight, sec_id) values (36, 'project', 0.5, 310);
insert into type (t_id, type, weight, sec_id) values (37, 'test', 0.3, 930);
insert into type (t_id, type, weight, sec_id) values (38, 'project', 0.4, 659);
insert into type (t_id, type, weight, sec_id) values (39, 'extra credit', 0.5, 342);
insert into type (t_id, type, weight, sec_id) values (40, 'extra credit', 0.2, 507);
insert into type (t_id, type, weight, sec_id) values (41, 'project', 0.6, 287);
insert into type (t_id, type, weight, sec_id) values (42, 'extra credit', 0.1, 262);
insert into type (t_id, type, weight, sec_id) values (43, 'homework', 0.0, 787);
insert into type (t_id, type, weight, sec_id) values (44, 'extra credit', 0.8, 44);
insert into type (t_id, type, weight, sec_id) values (45, 'extra credit', 0.0, 397);
insert into type (t_id, type, weight, sec_id) values (46, 'test', 0.5, 838);
insert into type (t_id, type, weight, sec_id) values (47, 'homework', 0.8, 131);
insert into type (t_id, type, weight, sec_id) values (48, 'homework', 0.2, 262);
insert into type (t_id, type, weight, sec_id) values (49, 'project', 1.0, 768);
insert into type (t_id, type, weight, sec_id) values (50, 'homework', 0.4, 135);
insert into type (t_id, type, weight, sec_id) values (51, 'extra credit', 0.8, 476);
insert into type (t_id, type, weight, sec_id) values (52, 'homework', 0.9, 99);
insert into type (t_id, type, weight, sec_id) values (53, 'test', 0.1, 362);
insert into type (t_id, type, weight, sec_id) values (54, 'test', 0.1, 36);
insert into type (t_id, type, weight, sec_id) values (55, 'test', 0.7, 962);
insert into type (t_id, type, weight, sec_id) values (56, 'extra credit', 0.1, 708);
insert into type (t_id, type, weight, sec_id) values (57, 'homework', 0.4, 420);
insert into type (t_id, type, weight, sec_id) values (58, 'extra credit', 0.4, 603);
insert into type (t_id, type, weight, sec_id) values (59, 'project', 0.3, 495);
insert into type (t_id, type, weight, sec_id) values (60, 'homework', 0.6, 161);
insert into type (t_id, type, weight, sec_id) values (61, 'homework', 0.1, 231);
insert into type (t_id, type, weight, sec_id) values (62, 'test', 1.0, 341);
insert into type (t_id, type, weight, sec_id) values (63, 'project', 0.9, 541);
insert into type (t_id, type, weight, sec_id) values (64, 'test', 0.7, 298);
insert into type (t_id, type, weight, sec_id) values (65, 'homework', 0.2, 344);
insert into type (t_id, type, weight, sec_id) values (66, 'project', 0.9, 979);
insert into type (t_id, type, weight, sec_id) values (67, 'extra credit', 0.9, 176);
insert into type (t_id, type, weight, sec_id) values (68, 'extra credit', 0.2, 468);
insert into type (t_id, type, weight, sec_id) values (69, 'homework', 0.6, 818);
insert into type (t_id, type, weight, sec_id) values (70, 'project', 1.0, 53);
insert into type (t_id, type, weight, sec_id) values (71, 'homework', 0.8, 615);
insert into type (t_id, type, weight, sec_id) values (72, 'extra credit', 0.3, 25);
insert into type (t_id, type, weight, sec_id) values (73, 'project', 0.9, 922);
insert into type (t_id, type, weight, sec_id) values (74, 'project', 0.5, 69);
insert into type (t_id, type, weight, sec_id) values (75, 'homework', 0.1, 225);
insert into type (t_id, type, weight, sec_id) values (76, 'test', 0.9, 735);
insert into type (t_id, type, weight, sec_id) values (77, 'homework', 0.1, 475);
insert into type (t_id, type, weight, sec_id) values (78, 'homework', 0.5, 794);
insert into type (t_id, type, weight, sec_id) values (79, 'extra credit', 1.0, 539);
insert into type (t_id, type, weight, sec_id) values (80, 'extra credit', 0.3, 85);
insert into type (t_id, type, weight, sec_id) values (81, 'homework', 0.2, 191);
insert into type (t_id, type, weight, sec_id) values (82, 'project', 0.3, 921);
insert into type (t_id, type, weight, sec_id) values (83, 'project', 0.4, 610);
insert into type (t_id, type, weight, sec_id) values (84, 'extra credit', 0.6, 701);
insert into type (t_id, type, weight, sec_id) values (85, 'extra credit', 0.5, 245);
insert into type (t_id, type, weight, sec_id) values (86, 'test', 0.3, 998);
insert into type (t_id, type, weight, sec_id) values (87, 'test', 0.4, 659);
insert into type (t_id, type, weight, sec_id) values (88, 'test', 0.9, 149);
insert into type (t_id, type, weight, sec_id) values (89, 'extra credit', 0.1, 107);
insert into type (t_id, type, weight, sec_id) values (90, 'test', 0.1, 907);
insert into type (t_id, type, weight, sec_id) values (91, 'project', 0.5, 408);
insert into type (t_id, type, weight, sec_id) values (92, 'test', 0.6, 220);
insert into type (t_id, type, weight, sec_id) values (93, 'project', 0.9, 384);
insert into type (t_id, type, weight, sec_id) values (94, 'extra credit', 0.7, 934);
insert into type (t_id, type, weight, sec_id) values (95, 'test', 0.6, 319);
insert into type (t_id, type, weight, sec_id) values (96, 'extra credit', 0.2, 442);
insert into type (t_id, type, weight, sec_id) values (97, 'test', 0.6, 682);
insert into type (t_id, type, weight, sec_id) values (98, 'project', 0.3, 740);
insert into type (t_id, type, weight, sec_id) values (99, 'test', 0.8, 61);
insert into type (t_id, type, weight, sec_id) values (100, 'test', 0.4, 251);
insert into type (t_id, type, weight, sec_id) values (101, 'test', 0.5, 867);
insert into type (t_id, type, weight, sec_id) values (102, 'extra credit', 0.2, 504);
insert into type (t_id, type, weight, sec_id) values (103, 'homework', 0.4, 467);
insert into type (t_id, type, weight, sec_id) values (104, 'extra credit', 0.7, 515);
insert into type (t_id, type, weight, sec_id) values (105, 'homework', 0.8, 895);
insert into type (t_id, type, weight, sec_id) values (106, 'homework', 0.8, 820);
insert into type (t_id, type, weight, sec_id) values (107, 'homework', 0.7, 537);
insert into type (t_id, type, weight, sec_id) values (108, 'extra credit', 0.8, 314);
insert into type (t_id, type, weight, sec_id) values (109, 'extra credit', 0.2, 693);
insert into type (t_id, type, weight, sec_id) values (110, 'extra credit', 0.0, 419);
insert into type (t_id, type, weight, sec_id) values (111, 'homework', 1.0, 715);
insert into type (t_id, type, weight, sec_id) values (112, 'homework', 0.6, 925);
insert into type (t_id, type, weight, sec_id) values (113, 'extra credit', 0.1, 626);
insert into type (t_id, type, weight, sec_id) values (114, 'extra credit', 0.4, 697);
insert into type (t_id, type, weight, sec_id) values (115, 'homework', 0.7, 346);
insert into type (t_id, type, weight, sec_id) values (116, 'project', 1.0, 181);
insert into type (t_id, type, weight, sec_id) values (117, 'test', 0.3, 44);
insert into type (t_id, type, weight, sec_id) values (118, 'project', 0.3, 465);
insert into type (t_id, type, weight, sec_id) values (119, 'homework', 0.5, 693);
insert into type (t_id, type, weight, sec_id) values (120, 'extra credit', 0.5, 498);
insert into type (t_id, type, weight, sec_id) values (121, 'homework', 0.4, 717);
insert into type (t_id, type, weight, sec_id) values (122, 'project', 0.7, 846);
insert into type (t_id, type, weight, sec_id) values (123, 'project', 0.9, 200);
insert into type (t_id, type, weight, sec_id) values (124, 'project', 1.0, 828);
insert into type (t_id, type, weight, sec_id) values (125, 'extra credit', 0.8, 263);
insert into type (t_id, type, weight, sec_id) values (126, 'test', 0.7, 944);
insert into type (t_id, type, weight, sec_id) values (127, 'project', 1.0, 984);
insert into type (t_id, type, weight, sec_id) values (128, 'extra credit', 0.0, 295);
insert into type (t_id, type, weight, sec_id) values (129, 'test', 0.4, 137);
insert into type (t_id, type, weight, sec_id) values (130, 'project', 0.2, 943);
insert into type (t_id, type, weight, sec_id) values (131, 'test', 0.2, 548);
insert into type (t_id, type, weight, sec_id) values (132, 'test', 0.2, 523);
insert into type (t_id, type, weight, sec_id) values (133, 'extra credit', 0.7, 801);
insert into type (t_id, type, weight, sec_id) values (134, 'test', 0.8, 324);
insert into type (t_id, type, weight, sec_id) values (135, 'homework', 0.6, 965);
insert into type (t_id, type, weight, sec_id) values (136, 'project', 0.9, 946);
insert into type (t_id, type, weight, sec_id) values (137, 'test', 0.7, 412);
insert into type (t_id, type, weight, sec_id) values (138, 'test', 0.7, 118);
insert into type (t_id, type, weight, sec_id) values (139, 'test', 0.4, 805);
insert into type (t_id, type, weight, sec_id) values (140, 'homework', 0.7, 697);
insert into type (t_id, type, weight, sec_id) values (141, 'extra credit', 0.5, 485);
insert into type (t_id, type, weight, sec_id) values (142, 'extra credit', 0.5, 991);
insert into type (t_id, type, weight, sec_id) values (143, 'project', 1.0, 407);
insert into type (t_id, type, weight, sec_id) values (144, 'homework', 0.4, 586);
insert into type (t_id, type, weight, sec_id) values (145, 'homework', 0.1, 418);
insert into type (t_id, type, weight, sec_id) values (146, 'extra credit', 0.7, 884);
insert into type (t_id, type, weight, sec_id) values (147, 'test', 0.9, 636);
insert into type (t_id, type, weight, sec_id) values (148, 'test', 0.8, 503);
insert into type (t_id, type, weight, sec_id) values (149, 'extra credit', 0.8, 608);
insert into type (t_id, type, weight, sec_id) values (150, 'homework', 0.9, 104);
insert into type (t_id, type, weight, sec_id) values (151, 'test', 0.2, 557);
insert into type (t_id, type, weight, sec_id) values (152, 'test', 0.9, 913);
insert into type (t_id, type, weight, sec_id) values (153, 'test', 0.5, 985);
insert into type (t_id, type, weight, sec_id) values (154, 'extra credit', 0.6, 80);
insert into type (t_id, type, weight, sec_id) values (155, 'homework', 0.9, 868);
insert into type (t_id, type, weight, sec_id) values (156, 'test', 0.7, 816);
insert into type (t_id, type, weight, sec_id) values (157, 'extra credit', 1.0, 345);
insert into type (t_id, type, weight, sec_id) values (158, 'test', 0.2, 240);
insert into type (t_id, type, weight, sec_id) values (159, 'homework', 0.9, 488);
insert into type (t_id, type, weight, sec_id) values (160, 'project', 0.8, 177);
insert into type (t_id, type, weight, sec_id) values (161, 'extra credit', 0.0, 21);
insert into type (t_id, type, weight, sec_id) values (162, 'project', 0.7, 300);
insert into type (t_id, type, weight, sec_id) values (163, 'homework', 0.8, 976);
insert into type (t_id, type, weight, sec_id) values (164, 'project', 0.0, 112);
insert into type (t_id, type, weight, sec_id) values (165, 'project', 0.3, 725);
insert into type (t_id, type, weight, sec_id) values (166, 'homework', 0.7, 904);
insert into type (t_id, type, weight, sec_id) values (167, 'project', 0.1, 29);
insert into type (t_id, type, weight, sec_id) values (168, 'project', 0.8, 690);
insert into type (t_id, type, weight, sec_id) values (169, 'project', 0.3, 698);
insert into type (t_id, type, weight, sec_id) values (170, 'homework', 0.8, 207);
insert into type (t_id, type, weight, sec_id) values (171, 'extra credit', 0.4, 122);
insert into type (t_id, type, weight, sec_id) values (172, 'test', 0.5, 552);
insert into type (t_id, type, weight, sec_id) values (173, 'homework', 0.1, 749);
insert into type (t_id, type, weight, sec_id) values (174, 'homework', 0.6, 809);
insert into type (t_id, type, weight, sec_id) values (175, 'homework', 0.9, 77);
insert into type (t_id, type, weight, sec_id) values (176, 'project', 0.6, 834);
insert into type (t_id, type, weight, sec_id) values (177, 'project', 0.4, 64);
insert into type (t_id, type, weight, sec_id) values (178, 'test', 0.9, 117);
insert into type (t_id, type, weight, sec_id) values (179, 'test', 0.7, 562);
insert into type (t_id, type, weight, sec_id) values (180, 'extra credit', 0.5, 750);
insert into type (t_id, type, weight, sec_id) values (181, 'project', 1.0, 301);
insert into type (t_id, type, weight, sec_id) values (182, 'test', 0.5, 632);
insert into type (t_id, type, weight, sec_id) values (183, 'extra credit', 0.0, 787);
insert into type (t_id, type, weight, sec_id) values (184, 'project', 0.4, 567);
insert into type (t_id, type, weight, sec_id) values (185, 'test', 0.7, 275);
insert into type (t_id, type, weight, sec_id) values (186, 'extra credit', 0.9, 486);
insert into type (t_id, type, weight, sec_id) values (187, 'project', 0.5, 320);
insert into type (t_id, type, weight, sec_id) values (188, 'homework', 0.1, 437);
insert into type (t_id, type, weight, sec_id) values (189, 'homework', 0.2, 698);
insert into type (t_id, type, weight, sec_id) values (190, 'project', 0.1, 980);
insert into type (t_id, type, weight, sec_id) values (191, 'test', 0.1, 888);
insert into type (t_id, type, weight, sec_id) values (192, 'project', 0.8, 342);
insert into type (t_id, type, weight, sec_id) values (193, 'homework', 0.0, 41);
insert into type (t_id, type, weight, sec_id) values (194, 'test', 0.6, 445);
insert into type (t_id, type, weight, sec_id) values (195, 'test', 0.3, 62);
insert into type (t_id, type, weight, sec_id) values (196, 'project', 0.6, 630);
insert into type (t_id, type, weight, sec_id) values (197, 'test', 0.6, 325);
insert into type (t_id, type, weight, sec_id) values (198, 'project', 0.8, 571);
insert into type (t_id, type, weight, sec_id) values (199, 'test', 0.4, 337);
insert into type (t_id, type, weight, sec_id) values (200, 'test', 0.9, 135);
insert into type (t_id, type, weight, sec_id) values (201, 'project', 0.8, 645);
insert into type (t_id, type, weight, sec_id) values (202, 'extra credit', 0.7, 285);
insert into type (t_id, type, weight, sec_id) values (203, 'test', 0.7, 481);
insert into type (t_id, type, weight, sec_id) values (204, 'homework', 0.8, 82);
insert into type (t_id, type, weight, sec_id) values (205, 'extra credit', 0.0, 301);
insert into type (t_id, type, weight, sec_id) values (206, 'test', 0.8, 16);
insert into type (t_id, type, weight, sec_id) values (207, 'project', 0.9, 239);
insert into type (t_id, type, weight, sec_id) values (208, 'test', 0.9, 959);
insert into type (t_id, type, weight, sec_id) values (209, 'extra credit', 0.9, 804);
insert into type (t_id, type, weight, sec_id) values (210, 'extra credit', 0.2, 931);
insert into type (t_id, type, weight, sec_id) values (211, 'homework', 0.3, 870);
insert into type (t_id, type, weight, sec_id) values (212, 'project', 0.7, 384);
insert into type (t_id, type, weight, sec_id) values (213, 'extra credit', 0.9, 368);
insert into type (t_id, type, weight, sec_id) values (214, 'extra credit', 0.2, 87);
insert into type (t_id, type, weight, sec_id) values (215, 'project', 0.7, 529);
insert into type (t_id, type, weight, sec_id) values (216, 'extra credit', 0.7, 806);
insert into type (t_id, type, weight, sec_id) values (217, 'project', 0.1, 699);
insert into type (t_id, type, weight, sec_id) values (218, 'test', 0.9, 777);
insert into type (t_id, type, weight, sec_id) values (219, 'extra credit', 0.0, 78);
insert into type (t_id, type, weight, sec_id) values (220, 'project', 0.6, 511);
insert into type (t_id, type, weight, sec_id) values (221, 'test', 0.1, 543);
insert into type (t_id, type, weight, sec_id) values (222, 'project', 0.2, 566);
insert into type (t_id, type, weight, sec_id) values (223, 'project', 0.2, 198);
insert into type (t_id, type, weight, sec_id) values (224, 'test', 0.6, 188);
insert into type (t_id, type, weight, sec_id) values (225, 'test', 0.3, 360);
insert into type (t_id, type, weight, sec_id) values (226, 'test', 0.9, 302);
insert into type (t_id, type, weight, sec_id) values (227, 'extra credit', 0.5, 604);
insert into type (t_id, type, weight, sec_id) values (228, 'test', 0.3, 352);
insert into type (t_id, type, weight, sec_id) values (229, 'extra credit', 0.7, 732);
insert into type (t_id, type, weight, sec_id) values (230, 'project', 0.3, 138);
insert into type (t_id, type, weight, sec_id) values (231, 'project', 0.5, 711);
insert into type (t_id, type, weight, sec_id) values (232, 'extra credit', 0.8, 363);
insert into type (t_id, type, weight, sec_id) values (233, 'homework', 0.1, 738);
insert into type (t_id, type, weight, sec_id) values (234, 'project', 1.0, 318);
insert into type (t_id, type, weight, sec_id) values (235, 'project', 0.1, 507);
insert into type (t_id, type, weight, sec_id) values (236, 'test', 0.7, 5);
insert into type (t_id, type, weight, sec_id) values (237, 'extra credit', 0.6, 664);
insert into type (t_id, type, weight, sec_id) values (238, 'homework', 0.1, 97);
insert into type (t_id, type, weight, sec_id) values (239, 'project', 0.4, 163);
insert into type (t_id, type, weight, sec_id) values (240, 'extra credit', 0.7, 771);
insert into type (t_id, type, weight, sec_id) values (241, 'test', 1.0, 876);
insert into type (t_id, type, weight, sec_id) values (242, 'extra credit', 0.0, 104);
insert into type (t_id, type, weight, sec_id) values (243, 'project', 0.2, 821);
insert into type (t_id, type, weight, sec_id) values (244, 'extra credit', 0.7, 219);
insert into type (t_id, type, weight, sec_id) values (245, 'extra credit', 0.1, 208);
insert into type (t_id, type, weight, sec_id) values (246, 'homework', 0.3, 63);
insert into type (t_id, type, weight, sec_id) values (247, 'test', 0.9, 600);
insert into type (t_id, type, weight, sec_id) values (248, 'homework', 0.4, 319);
insert into type (t_id, type, weight, sec_id) values (249, 'extra credit', 0.1, 786);
insert into type (t_id, type, weight, sec_id) values (250, 'project', 0.8, 829);
insert into type (t_id, type, weight, sec_id) values (251, 'homework', 0.9, 494);
insert into type (t_id, type, weight, sec_id) values (252, 'extra credit', 0.2, 521);
insert into type (t_id, type, weight, sec_id) values (253, 'test', 0.5, 124);
insert into type (t_id, type, weight, sec_id) values (254, 'test', 0.6, 180);
insert into type (t_id, type, weight, sec_id) values (255, 'homework', 0.8, 529);
insert into type (t_id, type, weight, sec_id) values (256, 'test', 0.3, 916);
insert into type (t_id, type, weight, sec_id) values (257, 'test', 0.0, 101);
insert into type (t_id, type, weight, sec_id) values (258, 'project', 0.3, 698);
insert into type (t_id, type, weight, sec_id) values (259, 'homework', 0.2, 35);
insert into type (t_id, type, weight, sec_id) values (260, 'test', 0.7, 290);
insert into type (t_id, type, weight, sec_id) values (261, 'project', 0.3, 347);
insert into type (t_id, type, weight, sec_id) values (262, 'homework', 0.1, 77);
insert into type (t_id, type, weight, sec_id) values (263, 'homework', 0.4, 796);
insert into type (t_id, type, weight, sec_id) values (264, 'extra credit', 0.9, 411);
insert into type (t_id, type, weight, sec_id) values (265, 'test', 0.8, 477);
insert into type (t_id, type, weight, sec_id) values (266, 'project', 0.6, 898);
insert into type (t_id, type, weight, sec_id) values (267, 'test', 1.0, 318);
insert into type (t_id, type, weight, sec_id) values (268, 'extra credit', 0.5, 609);
insert into type (t_id, type, weight, sec_id) values (269, 'extra credit', 0.4, 327);
insert into type (t_id, type, weight, sec_id) values (270, 'project', 0.5, 172);
insert into type (t_id, type, weight, sec_id) values (271, 'extra credit', 0.5, 2);
insert into type (t_id, type, weight, sec_id) values (272, 'homework', 0.6, 368);
insert into type (t_id, type, weight, sec_id) values (273, 'project', 0.4, 613);
insert into type (t_id, type, weight, sec_id) values (274, 'project', 0.3, 883);
insert into type (t_id, type, weight, sec_id) values (275, 'project', 0.3, 995);
insert into type (t_id, type, weight, sec_id) values (276, 'homework', 0.5, 231);
insert into type (t_id, type, weight, sec_id) values (277, 'test', 0.4, 654);
insert into type (t_id, type, weight, sec_id) values (278, 'test', 0.7, 819);
insert into type (t_id, type, weight, sec_id) values (279, 'project', 1.0, 126);
insert into type (t_id, type, weight, sec_id) values (280, 'test', 0.3, 593);
insert into type (t_id, type, weight, sec_id) values (281, 'test', 0.5, 962);
insert into type (t_id, type, weight, sec_id) values (282, 'homework', 0.5, 487);
insert into type (t_id, type, weight, sec_id) values (283, 'homework', 0.3, 453);
insert into type (t_id, type, weight, sec_id) values (284, 'test', 0.4, 607);
insert into type (t_id, type, weight, sec_id) values (285, 'test', 0.0, 238);
insert into type (t_id, type, weight, sec_id) values (286, 'homework', 0.0, 291);
insert into type (t_id, type, weight, sec_id) values (287, 'homework', 0.9, 761);
insert into type (t_id, type, weight, sec_id) values (288, 'homework', 0.6, 652);
insert into type (t_id, type, weight, sec_id) values (289, 'test', 0.8, 508);
insert into type (t_id, type, weight, sec_id) values (290, 'extra credit', 0.7, 489);
insert into type (t_id, type, weight, sec_id) values (291, 'extra credit', 0.7, 153);
insert into type (t_id, type, weight, sec_id) values (292, 'test', 0.5, 575);
insert into type (t_id, type, weight, sec_id) values (293, 'project', 0.7, 342);
insert into type (t_id, type, weight, sec_id) values (294, 'homework', 0.5, 730);
insert into type (t_id, type, weight, sec_id) values (295, 'homework', 0.8, 168);
insert into type (t_id, type, weight, sec_id) values (296, 'homework', 0.9, 835);
insert into type (t_id, type, weight, sec_id) values (297, 'test', 0.8, 670);
insert into type (t_id, type, weight, sec_id) values (298, 'homework', 0.6, 557);
insert into type (t_id, type, weight, sec_id) values (299, 'project', 0.5, 392);
insert into type (t_id, type, weight, sec_id) values (300, 'extra credit', 0.0, 551);
insert into type (t_id, type, weight, sec_id) values (301, 'test', 0.3, 891);
insert into type (t_id, type, weight, sec_id) values (302, 'project', 0.7, 994);
insert into type (t_id, type, weight, sec_id) values (303, 'extra credit', 0.7, 856);
insert into type (t_id, type, weight, sec_id) values (304, 'homework', 0.2, 526);
insert into type (t_id, type, weight, sec_id) values (305, 'project', 0.7, 841);
insert into type (t_id, type, weight, sec_id) values (306, 'project', 0.8, 764);
insert into type (t_id, type, weight, sec_id) values (307, 'extra credit', 0.6, 588);
insert into type (t_id, type, weight, sec_id) values (308, 'extra credit', 0.7, 277);
insert into type (t_id, type, weight, sec_id) values (309, 'extra credit', 0.8, 395);
insert into type (t_id, type, weight, sec_id) values (310, 'project', 0.2, 113);
insert into type (t_id, type, weight, sec_id) values (311, 'test', 0.2, 35);
insert into type (t_id, type, weight, sec_id) values (312, 'extra credit', 0.0, 125);
insert into type (t_id, type, weight, sec_id) values (313, 'homework', 0.7, 698);
insert into type (t_id, type, weight, sec_id) values (314, 'homework', 0.7, 59);
insert into type (t_id, type, weight, sec_id) values (315, 'homework', 0.7, 269);
insert into type (t_id, type, weight, sec_id) values (316, 'project', 0.5, 961);
insert into type (t_id, type, weight, sec_id) values (317, 'extra credit', 0.6, 447);
insert into type (t_id, type, weight, sec_id) values (318, 'project', 0.2, 867);
insert into type (t_id, type, weight, sec_id) values (319, 'project', 0.3, 92);
insert into type (t_id, type, weight, sec_id) values (320, 'project', 0.3, 491);
insert into type (t_id, type, weight, sec_id) values (321, 'extra credit', 0.6, 242);
insert into type (t_id, type, weight, sec_id) values (322, 'project', 0.5, 905);
insert into type (t_id, type, weight, sec_id) values (323, 'extra credit', 0.6, 814);
insert into type (t_id, type, weight, sec_id) values (324, 'project', 0.5, 609);
insert into type (t_id, type, weight, sec_id) values (325, 'test', 0.5, 970);
insert into type (t_id, type, weight, sec_id) values (326, 'test', 0.9, 267);
insert into type (t_id, type, weight, sec_id) values (327, 'extra credit', 0.4, 507);
insert into type (t_id, type, weight, sec_id) values (328, 'extra credit', 0.3, 305);
insert into type (t_id, type, weight, sec_id) values (329, 'test', 0.6, 643);
insert into type (t_id, type, weight, sec_id) values (330, 'test', 0.3, 36);
insert into type (t_id, type, weight, sec_id) values (331, 'extra credit', 0.9, 632);
insert into type (t_id, type, weight, sec_id) values (332, 'project', 0.6, 677);
insert into type (t_id, type, weight, sec_id) values (333, 'project', 0.5, 397);
insert into type (t_id, type, weight, sec_id) values (334, 'test', 0.8, 852);
insert into type (t_id, type, weight, sec_id) values (335, 'extra credit', 0.9, 472);
insert into type (t_id, type, weight, sec_id) values (336, 'homework', 1.0, 685);
insert into type (t_id, type, weight, sec_id) values (337, 'test', 0.7, 502);
insert into type (t_id, type, weight, sec_id) values (338, 'test', 0.8, 97);
insert into type (t_id, type, weight, sec_id) values (339, 'project', 0.4, 87);
insert into type (t_id, type, weight, sec_id) values (340, 'project', 0.2, 189);
insert into type (t_id, type, weight, sec_id) values (341, 'test', 0.2, 195);
insert into type (t_id, type, weight, sec_id) values (342, 'test', 0.4, 535);
insert into type (t_id, type, weight, sec_id) values (343, 'homework', 0.1, 765);
insert into type (t_id, type, weight, sec_id) values (344, 'homework', 0.7, 278);
insert into type (t_id, type, weight, sec_id) values (345, 'test', 0.8, 769);
insert into type (t_id, type, weight, sec_id) values (346, 'homework', 0.5, 974);
insert into type (t_id, type, weight, sec_id) values (347, 'project', 0.1, 536);
insert into type (t_id, type, weight, sec_id) values (348, 'homework', 0.5, 379);
insert into type (t_id, type, weight, sec_id) values (349, 'extra credit', 0.7, 472);
insert into type (t_id, type, weight, sec_id) values (350, 'extra credit', 0.5, 866);
insert into type (t_id, type, weight, sec_id) values (351, 'project', 0.9, 42);
insert into type (t_id, type, weight, sec_id) values (352, 'test', 0.8, 884);
insert into type (t_id, type, weight, sec_id) values (353, 'test', 0.6, 74);
insert into type (t_id, type, weight, sec_id) values (354, 'test', 0.5, 602);
insert into type (t_id, type, weight, sec_id) values (355, 'project', 0.7, 834);
insert into type (t_id, type, weight, sec_id) values (356, 'project', 0.3, 827);
insert into type (t_id, type, weight, sec_id) values (357, 'project', 0.4, 984);
insert into type (t_id, type, weight, sec_id) values (358, 'extra credit', 0.6, 32);
insert into type (t_id, type, weight, sec_id) values (359, 'test', 0.8, 466);
insert into type (t_id, type, weight, sec_id) values (360, 'extra credit', 0.8, 772);
insert into type (t_id, type, weight, sec_id) values (361, 'extra credit', 0.3, 436);
insert into type (t_id, type, weight, sec_id) values (362, 'test', 0.2, 381);
insert into type (t_id, type, weight, sec_id) values (363, 'test', 0.8, 708);
insert into type (t_id, type, weight, sec_id) values (364, 'test', 0.7, 288);
insert into type (t_id, type, weight, sec_id) values (365, 'test', 0.0, 215);
insert into type (t_id, type, weight, sec_id) values (366, 'homework', 1.0, 939);
insert into type (t_id, type, weight, sec_id) values (367, 'homework', 0.3, 138);
insert into type (t_id, type, weight, sec_id) values (368, 'extra credit', 0.9, 427);
insert into type (t_id, type, weight, sec_id) values (369, 'project', 1.0, 256);
insert into type (t_id, type, weight, sec_id) values (370, 'test', 0.6, 909);
insert into type (t_id, type, weight, sec_id) values (371, 'project', 0.0, 445);
insert into type (t_id, type, weight, sec_id) values (372, 'homework', 0.6, 837);
insert into type (t_id, type, weight, sec_id) values (373, 'extra credit', 0.4, 74);
insert into type (t_id, type, weight, sec_id) values (374, 'extra credit', 0.7, 784);
insert into type (t_id, type, weight, sec_id) values (375, 'project', 0.5, 769);
insert into type (t_id, type, weight, sec_id) values (376, 'project', 0.2, 902);
insert into type (t_id, type, weight, sec_id) values (377, 'homework', 1.0, 292);
insert into type (t_id, type, weight, sec_id) values (378, 'extra credit', 0.8, 237);
insert into type (t_id, type, weight, sec_id) values (379, 'extra credit', 0.5, 964);
insert into type (t_id, type, weight, sec_id) values (380, 'extra credit', 0.1, 918);
insert into type (t_id, type, weight, sec_id) values (381, 'extra credit', 0.6, 574);
insert into type (t_id, type, weight, sec_id) values (382, 'extra credit', 0.4, 15);
insert into type (t_id, type, weight, sec_id) values (383, 'project', 0.4, 937);
insert into type (t_id, type, weight, sec_id) values (384, 'extra credit', 0.5, 90);
insert into type (t_id, type, weight, sec_id) values (385, 'extra credit', 0.1, 235);
insert into type (t_id, type, weight, sec_id) values (386, 'project', 0.7, 118);
insert into type (t_id, type, weight, sec_id) values (387, 'homework', 0.6, 693);
insert into type (t_id, type, weight, sec_id) values (388, 'homework', 0.2, 898);
insert into type (t_id, type, weight, sec_id) values (389, 'homework', 0.4, 639);
insert into type (t_id, type, weight, sec_id) values (390, 'project', 0.5, 745);
insert into type (t_id, type, weight, sec_id) values (391, 'test', 0.7, 705);
insert into type (t_id, type, weight, sec_id) values (392, 'project', 0.9, 913);
insert into type (t_id, type, weight, sec_id) values (393, 'extra credit', 0.6, 466);
insert into type (t_id, type, weight, sec_id) values (394, 'homework', 0.3, 73);
insert into type (t_id, type, weight, sec_id) values (395, 'extra credit', 0.2, 788);
insert into type (t_id, type, weight, sec_id) values (396, 'project', 0.6, 332);
insert into type (t_id, type, weight, sec_id) values (397, 'project', 0.9, 326);
insert into type (t_id, type, weight, sec_id) values (398, 'project', 1.0, 642);
insert into type (t_id, type, weight, sec_id) values (399, 'test', 0.5, 969);
insert into type (t_id, type, weight, sec_id) values (400, 'test', 0.4, 174);
insert into type (t_id, type, weight, sec_id) values (401, 'project', 0.3, 188);
insert into type (t_id, type, weight, sec_id) values (402, 'test', 0.9, 553);
insert into type (t_id, type, weight, sec_id) values (403, 'homework', 0.9, 519);
insert into type (t_id, type, weight, sec_id) values (404, 'extra credit', 1.0, 705);
insert into type (t_id, type, weight, sec_id) values (405, 'homework', 0.6, 22);
insert into type (t_id, type, weight, sec_id) values (406, 'project', 0.2, 791);
insert into type (t_id, type, weight, sec_id) values (407, 'project', 0.5, 922);
insert into type (t_id, type, weight, sec_id) values (408, 'test', 0.3, 544);
insert into type (t_id, type, weight, sec_id) values (409, 'test', 0.7, 954);
insert into type (t_id, type, weight, sec_id) values (410, 'test', 0.4, 319);
insert into type (t_id, type, weight, sec_id) values (411, 'extra credit', 0.9, 448);
insert into type (t_id, type, weight, sec_id) values (412, 'project', 0.1, 800);
insert into type (t_id, type, weight, sec_id) values (413, 'homework', 0.6, 411);
insert into type (t_id, type, weight, sec_id) values (414, 'homework', 0.8, 959);
insert into type (t_id, type, weight, sec_id) values (415, 'test', 0.7, 142);
insert into type (t_id, type, weight, sec_id) values (416, 'project', 0.3, 117);
insert into type (t_id, type, weight, sec_id) values (417, 'project', 0.7, 187);
insert into type (t_id, type, weight, sec_id) values (418, 'project', 0.6, 628);
insert into type (t_id, type, weight, sec_id) values (419, 'project', 0.6, 315);
insert into type (t_id, type, weight, sec_id) values (420, 'extra credit', 0.3, 626);
insert into type (t_id, type, weight, sec_id) values (421, 'homework', 0.1, 335);
insert into type (t_id, type, weight, sec_id) values (422, 'homework', 0.2, 689);
insert into type (t_id, type, weight, sec_id) values (423, 'project', 0.8, 423);
insert into type (t_id, type, weight, sec_id) values (424, 'test', 0.7, 40);
insert into type (t_id, type, weight, sec_id) values (425, 'test', 0.2, 95);
insert into type (t_id, type, weight, sec_id) values (426, 'extra credit', 0.9, 524);
insert into type (t_id, type, weight, sec_id) values (427, 'homework', 0.8, 922);
insert into type (t_id, type, weight, sec_id) values (428, 'project', 0.5, 462);
insert into type (t_id, type, weight, sec_id) values (429, 'test', 0.4, 509);
insert into type (t_id, type, weight, sec_id) values (430, 'project', 0.5, 161);
insert into type (t_id, type, weight, sec_id) values (431, 'extra credit', 0.1, 410);
insert into type (t_id, type, weight, sec_id) values (432, 'project', 0.2, 592);
insert into type (t_id, type, weight, sec_id) values (433, 'extra credit', 0.9, 291);
insert into type (t_id, type, weight, sec_id) values (434, 'homework', 1.0, 662);
insert into type (t_id, type, weight, sec_id) values (435, 'homework', 0.9, 783);
insert into type (t_id, type, weight, sec_id) values (436, 'project', 0.3, 111);
insert into type (t_id, type, weight, sec_id) values (437, 'test', 1.0, 444);
insert into type (t_id, type, weight, sec_id) values (438, 'test', 0.7, 672);
insert into type (t_id, type, weight, sec_id) values (439, 'project', 0.2, 161);
insert into type (t_id, type, weight, sec_id) values (440, 'homework', 0.0, 390);
insert into type (t_id, type, weight, sec_id) values (441, 'homework', 0.1, 361);
insert into type (t_id, type, weight, sec_id) values (442, 'homework', 0.9, 967);
insert into type (t_id, type, weight, sec_id) values (443, 'extra credit', 1.0, 854);
insert into type (t_id, type, weight, sec_id) values (444, 'extra credit', 0.5, 786);
insert into type (t_id, type, weight, sec_id) values (445, 'test', 0.8, 850);
insert into type (t_id, type, weight, sec_id) values (446, 'homework', 0.2, 264);
insert into type (t_id, type, weight, sec_id) values (447, 'test', 0.7, 335);
insert into type (t_id, type, weight, sec_id) values (448, 'extra credit', 0.4, 787);
insert into type (t_id, type, weight, sec_id) values (449, 'homework', 0.7, 453);
insert into type (t_id, type, weight, sec_id) values (450, 'test', 0.5, 995);
insert into type (t_id, type, weight, sec_id) values (451, 'homework', 0.8, 834);
insert into type (t_id, type, weight, sec_id) values (452, 'extra credit', 0.3, 882);
insert into type (t_id, type, weight, sec_id) values (453, 'extra credit', 0.2, 982);
insert into type (t_id, type, weight, sec_id) values (454, 'test', 0.3, 865);
insert into type (t_id, type, weight, sec_id) values (455, 'homework', 0.7, 298);
insert into type (t_id, type, weight, sec_id) values (456, 'homework', 0.3, 977);
insert into type (t_id, type, weight, sec_id) values (457, 'extra credit', 0.5, 473);
insert into type (t_id, type, weight, sec_id) values (458, 'homework', 0.9, 549);
insert into type (t_id, type, weight, sec_id) values (459, 'test', 0.7, 151);
insert into type (t_id, type, weight, sec_id) values (460, 'project', 0.8, 816);
insert into type (t_id, type, weight, sec_id) values (461, 'extra credit', 0.2, 383);
insert into type (t_id, type, weight, sec_id) values (462, 'project', 0.9, 27);
insert into type (t_id, type, weight, sec_id) values (463, 'test', 0.1, 1);
insert into type (t_id, type, weight, sec_id) values (464, 'homework', 0.8, 499);
insert into type (t_id, type, weight, sec_id) values (465, 'project', 0.7, 65);
insert into type (t_id, type, weight, sec_id) values (466, 'test', 0.4, 829);
insert into type (t_id, type, weight, sec_id) values (467, 'project', 0.3, 372);
insert into type (t_id, type, weight, sec_id) values (468, 'test', 0.7, 337);
insert into type (t_id, type, weight, sec_id) values (469, 'test', 0.4, 251);
insert into type (t_id, type, weight, sec_id) values (470, 'project', 0.2, 210);
insert into type (t_id, type, weight, sec_id) values (471, 'homework', 0.7, 765);
insert into type (t_id, type, weight, sec_id) values (472, 'extra credit', 0.7, 967);
insert into type (t_id, type, weight, sec_id) values (473, 'project', 0.8, 485);
insert into type (t_id, type, weight, sec_id) values (474, 'homework', 0.9, 720);
insert into type (t_id, type, weight, sec_id) values (475, 'project', 0.5, 279);
insert into type (t_id, type, weight, sec_id) values (476, 'test', 0.4, 99);
insert into type (t_id, type, weight, sec_id) values (477, 'project', 0.2, 53);
insert into type (t_id, type, weight, sec_id) values (478, 'homework', 0.9, 592);
insert into type (t_id, type, weight, sec_id) values (479, 'test', 0.8, 529);
insert into type (t_id, type, weight, sec_id) values (480, 'homework', 0.9, 204);
insert into type (t_id, type, weight, sec_id) values (481, 'test', 0.3, 111);
insert into type (t_id, type, weight, sec_id) values (482, 'extra credit', 0.0, 664);
insert into type (t_id, type, weight, sec_id) values (483, 'project', 0.5, 657);
insert into type (t_id, type, weight, sec_id) values (484, 'test', 0.9, 95);
insert into type (t_id, type, weight, sec_id) values (485, 'extra credit', 0.6, 675);
insert into type (t_id, type, weight, sec_id) values (486, 'homework', 0.9, 867);
insert into type (t_id, type, weight, sec_id) values (487, 'extra credit', 0.2, 536);
insert into type (t_id, type, weight, sec_id) values (488, 'test', 0.3, 81);
insert into type (t_id, type, weight, sec_id) values (489, 'homework', 0.3, 447);
insert into type (t_id, type, weight, sec_id) values (490, 'homework', 0.9, 754);
insert into type (t_id, type, weight, sec_id) values (491, 'extra credit', 0.3, 102);
insert into type (t_id, type, weight, sec_id) values (492, 'extra credit', 0.7, 57);
insert into type (t_id, type, weight, sec_id) values (493, 'project', 0.3, 777);
insert into type (t_id, type, weight, sec_id) values (494, 'test', 0.3, 394);
insert into type (t_id, type, weight, sec_id) values (495, 'project', 0.7, 533);
insert into type (t_id, type, weight, sec_id) values (496, 'project', 0.0, 253);
insert into type (t_id, type, weight, sec_id) values (497, 'test', 0.4, 875);
insert into type (t_id, type, weight, sec_id) values (498, 'homework', 0.7, 529);
insert into type (t_id, type, weight, sec_id) values (499, 'homework', 0.5, 111);
insert into type (t_id, type, weight, sec_id) values (500, 'project', 0.3, 965);
insert into type (t_id, type, weight, sec_id) values (501, 'extra credit', 0.9, 428);
insert into type (t_id, type, weight, sec_id) values (502, 'homework', 0.1, 449);
insert into type (t_id, type, weight, sec_id) values (503, 'test', 0.9, 564);
insert into type (t_id, type, weight, sec_id) values (504, 'extra credit', 0.0, 441);
insert into type (t_id, type, weight, sec_id) values (505, 'extra credit', 0.8, 406);
insert into type (t_id, type, weight, sec_id) values (506, 'test', 0.6, 995);
insert into type (t_id, type, weight, sec_id) values (507, 'homework', 0.5, 868);
insert into type (t_id, type, weight, sec_id) values (508, 'homework', 0.2, 38);
insert into type (t_id, type, weight, sec_id) values (509, 'test', 0.1, 460);
insert into type (t_id, type, weight, sec_id) values (510, 'homework', 0.1, 27);
insert into type (t_id, type, weight, sec_id) values (511, 'extra credit', 0.6, 128);
insert into type (t_id, type, weight, sec_id) values (512, 'project', 0.8, 463);
insert into type (t_id, type, weight, sec_id) values (513, 'homework', 0.3, 381);
insert into type (t_id, type, weight, sec_id) values (514, 'project', 0.6, 567);
insert into type (t_id, type, weight, sec_id) values (515, 'test', 0.4, 573);
insert into type (t_id, type, weight, sec_id) values (516, 'extra credit', 0.1, 702);
insert into type (t_id, type, weight, sec_id) values (517, 'project', 0.2, 935);
insert into type (t_id, type, weight, sec_id) values (518, 'project', 0.8, 410);
insert into type (t_id, type, weight, sec_id) values (519, 'extra credit', 0.3, 984);
insert into type (t_id, type, weight, sec_id) values (520, 'extra credit', 0.4, 53);
insert into type (t_id, type, weight, sec_id) values (521, 'project', 0.6, 217);
insert into type (t_id, type, weight, sec_id) values (522, 'extra credit', 0.0, 361);
insert into type (t_id, type, weight, sec_id) values (523, 'test', 0.4, 163);
insert into type (t_id, type, weight, sec_id) values (524, 'homework', 0.3, 529);
insert into type (t_id, type, weight, sec_id) values (525, 'project', 0.6, 227);
insert into type (t_id, type, weight, sec_id) values (526, 'test', 0.3, 913);
insert into type (t_id, type, weight, sec_id) values (527, 'extra credit', 0.7, 389);
insert into type (t_id, type, weight, sec_id) values (528, 'project', 0.0, 198);
insert into type (t_id, type, weight, sec_id) values (529, 'extra credit', 0.5, 549);
insert into type (t_id, type, weight, sec_id) values (530, 'extra credit', 0.5, 457);
insert into type (t_id, type, weight, sec_id) values (531, 'homework', 0.4, 873);
insert into type (t_id, type, weight, sec_id) values (532, 'project', 0.5, 140);
insert into type (t_id, type, weight, sec_id) values (533, 'project', 0.4, 754);
insert into type (t_id, type, weight, sec_id) values (534, 'test', 0.3, 834);
insert into type (t_id, type, weight, sec_id) values (535, 'extra credit', 0.6, 385);
insert into type (t_id, type, weight, sec_id) values (536, 'extra credit', 0.3, 490);
insert into type (t_id, type, weight, sec_id) values (537, 'test', 0.8, 304);
insert into type (t_id, type, weight, sec_id) values (538, 'homework', 0.5, 807);
insert into type (t_id, type, weight, sec_id) values (539, 'extra credit', 0.2, 229);
insert into type (t_id, type, weight, sec_id) values (540, 'project', 0.7, 915);
insert into type (t_id, type, weight, sec_id) values (541, 'test', 0.3, 889);
insert into type (t_id, type, weight, sec_id) values (542, 'project', 0.6, 927);
insert into type (t_id, type, weight, sec_id) values (543, 'homework', 0.6, 644);
insert into type (t_id, type, weight, sec_id) values (544, 'project', 0.4, 822);
insert into type (t_id, type, weight, sec_id) values (545, 'project', 0.4, 157);
insert into type (t_id, type, weight, sec_id) values (546, 'test', 0.7, 586);
insert into type (t_id, type, weight, sec_id) values (547, 'homework', 0.2, 813);
insert into type (t_id, type, weight, sec_id) values (548, 'extra credit', 0.3, 956);
insert into type (t_id, type, weight, sec_id) values (549, 'homework', 0.9, 969);
insert into type (t_id, type, weight, sec_id) values (550, 'project', 0.5, 100);
insert into type (t_id, type, weight, sec_id) values (551, 'extra credit', 0.1, 644);
insert into type (t_id, type, weight, sec_id) values (552, 'project', 0.2, 146);
insert into type (t_id, type, weight, sec_id) values (553, 'extra credit', 0.7, 345);
insert into type (t_id, type, weight, sec_id) values (554, 'homework', 0.2, 534);
insert into type (t_id, type, weight, sec_id) values (555, 'project', 0.7, 544);
insert into type (t_id, type, weight, sec_id) values (556, 'homework', 0.4, 4);
insert into type (t_id, type, weight, sec_id) values (557, 'homework', 0.4, 642);
insert into type (t_id, type, weight, sec_id) values (558, 'homework', 0.2, 664);
insert into type (t_id, type, weight, sec_id) values (559, 'project', 0.9, 908);
insert into type (t_id, type, weight, sec_id) values (560, 'test', 0.4, 528);
insert into type (t_id, type, weight, sec_id) values (561, 'test', 0.7, 982);
insert into type (t_id, type, weight, sec_id) values (562, 'extra credit', 0.8, 933);
insert into type (t_id, type, weight, sec_id) values (563, 'test', 0.7, 105);
insert into type (t_id, type, weight, sec_id) values (564, 'extra credit', 0.9, 427);
insert into type (t_id, type, weight, sec_id) values (565, 'extra credit', 1.0, 71);
insert into type (t_id, type, weight, sec_id) values (566, 'homework', 0.4, 843);
insert into type (t_id, type, weight, sec_id) values (567, 'extra credit', 0.2, 196);
insert into type (t_id, type, weight, sec_id) values (568, 'test', 0.6, 43);
insert into type (t_id, type, weight, sec_id) values (569, 'project', 0.8, 585);
insert into type (t_id, type, weight, sec_id) values (570, 'homework', 0.7, 303);
insert into type (t_id, type, weight, sec_id) values (571, 'homework', 0.4, 326);
insert into type (t_id, type, weight, sec_id) values (572, 'test', 0.6, 68);
insert into type (t_id, type, weight, sec_id) values (573, 'extra credit', 0.1, 781);
insert into type (t_id, type, weight, sec_id) values (574, 'homework', 0.5, 311);
insert into type (t_id, type, weight, sec_id) values (575, 'homework', 0.4, 315);
insert into type (t_id, type, weight, sec_id) values (576, 'project', 0.3, 173);
insert into type (t_id, type, weight, sec_id) values (577, 'test', 0.2, 758);
insert into type (t_id, type, weight, sec_id) values (578, 'project', 0.5, 500);
insert into type (t_id, type, weight, sec_id) values (579, 'homework', 0.2, 40);
insert into type (t_id, type, weight, sec_id) values (580, 'homework', 0.0, 866);
insert into type (t_id, type, weight, sec_id) values (581, 'extra credit', 0.0, 480);
insert into type (t_id, type, weight, sec_id) values (582, 'homework', 0.5, 566);
insert into type (t_id, type, weight, sec_id) values (583, 'project', 0.2, 351);
insert into type (t_id, type, weight, sec_id) values (584, 'extra credit', 0.4, 210);
insert into type (t_id, type, weight, sec_id) values (585, 'test', 0.6, 456);
insert into type (t_id, type, weight, sec_id) values (586, 'project', 0.8, 526);
insert into type (t_id, type, weight, sec_id) values (587, 'project', 0.9, 772);
insert into type (t_id, type, weight, sec_id) values (588, 'test', 1.0, 152);
insert into type (t_id, type, weight, sec_id) values (589, 'project', 1.0, 439);
insert into type (t_id, type, weight, sec_id) values (590, 'project', 1.0, 473);
insert into type (t_id, type, weight, sec_id) values (591, 'homework', 0.5, 740);
insert into type (t_id, type, weight, sec_id) values (592, 'test', 0.7, 213);
insert into type (t_id, type, weight, sec_id) values (593, 'homework', 0.8, 394);
insert into type (t_id, type, weight, sec_id) values (594, 'test', 0.1, 928);
insert into type (t_id, type, weight, sec_id) values (595, 'extra credit', 0.1, 732);
insert into type (t_id, type, weight, sec_id) values (596, 'extra credit', 0.5, 308);
insert into type (t_id, type, weight, sec_id) values (597, 'test', 0.5, 477);
insert into type (t_id, type, weight, sec_id) values (598, 'homework', 0.6, 392);
insert into type (t_id, type, weight, sec_id) values (599, 'project', 0.4, 567);
insert into type (t_id, type, weight, sec_id) values (600, 'extra credit', 0.9, 19);
insert into type (t_id, type, weight, sec_id) values (601, 'test', 0.3, 720);
insert into type (t_id, type, weight, sec_id) values (602, 'project', 0.6, 745);
insert into type (t_id, type, weight, sec_id) values (603, 'test', 1.0, 343);
insert into type (t_id, type, weight, sec_id) values (604, 'project', 0.8, 285);
insert into type (t_id, type, weight, sec_id) values (605, 'test', 0.2, 231);
insert into type (t_id, type, weight, sec_id) values (606, 'extra credit', 0.6, 550);
insert into type (t_id, type, weight, sec_id) values (607, 'extra credit', 0.3, 623);
insert into type (t_id, type, weight, sec_id) values (608, 'project', 0.5, 559);
insert into type (t_id, type, weight, sec_id) values (609, 'project', 0.5, 103);
insert into type (t_id, type, weight, sec_id) values (610, 'homework', 0.2, 799);
insert into type (t_id, type, weight, sec_id) values (611, 'extra credit', 0.3, 798);
insert into type (t_id, type, weight, sec_id) values (612, 'extra credit', 0.5, 955);
insert into type (t_id, type, weight, sec_id) values (613, 'homework', 0.4, 711);
insert into type (t_id, type, weight, sec_id) values (614, 'extra credit', 0.4, 132);
insert into type (t_id, type, weight, sec_id) values (615, 'project', 0.6, 435);
insert into type (t_id, type, weight, sec_id) values (616, 'homework', 0.3, 215);
insert into type (t_id, type, weight, sec_id) values (617, 'homework', 0.7, 106);
insert into type (t_id, type, weight, sec_id) values (618, 'homework', 1.0, 335);
insert into type (t_id, type, weight, sec_id) values (619, 'test', 0.6, 93);
insert into type (t_id, type, weight, sec_id) values (620, 'homework', 0.9, 281);
insert into type (t_id, type, weight, sec_id) values (621, 'project', 0.9, 230);
insert into type (t_id, type, weight, sec_id) values (622, 'test', 0.9, 633);
insert into type (t_id, type, weight, sec_id) values (623, 'project', 0.2, 588);
insert into type (t_id, type, weight, sec_id) values (624, 'extra credit', 0.1, 230);
insert into type (t_id, type, weight, sec_id) values (625, 'extra credit', 0.2, 164);
insert into type (t_id, type, weight, sec_id) values (626, 'extra credit', 0.8, 580);
insert into type (t_id, type, weight, sec_id) values (627, 'extra credit', 0.1, 609);
insert into type (t_id, type, weight, sec_id) values (628, 'project', 0.8, 27);
insert into type (t_id, type, weight, sec_id) values (629, 'test', 0.6, 297);
insert into type (t_id, type, weight, sec_id) values (630, 'project', 0.4, 354);
insert into type (t_id, type, weight, sec_id) values (631, 'test', 0.1, 143);
insert into type (t_id, type, weight, sec_id) values (632, 'project', 0.7, 786);
insert into type (t_id, type, weight, sec_id) values (633, 'test', 0.9, 214);
insert into type (t_id, type, weight, sec_id) values (634, 'extra credit', 0.2, 349);
insert into type (t_id, type, weight, sec_id) values (635, 'test', 0.5, 227);
insert into type (t_id, type, weight, sec_id) values (636, 'homework', 0.8, 543);
insert into type (t_id, type, weight, sec_id) values (637, 'extra credit', 0.8, 208);
insert into type (t_id, type, weight, sec_id) values (638, 'test', 0.9, 332);
insert into type (t_id, type, weight, sec_id) values (639, 'test', 0.1, 974);
insert into type (t_id, type, weight, sec_id) values (640, 'test', 0.2, 123);
insert into type (t_id, type, weight, sec_id) values (641, 'extra credit', 0.8, 622);
insert into type (t_id, type, weight, sec_id) values (642, 'homework', 0.8, 882);
insert into type (t_id, type, weight, sec_id) values (643, 'project', 0.5, 571);
insert into type (t_id, type, weight, sec_id) values (644, 'homework', 0.5, 750);
insert into type (t_id, type, weight, sec_id) values (645, 'extra credit', 0.3, 114);
insert into type (t_id, type, weight, sec_id) values (646, 'test', 1.0, 597);
insert into type (t_id, type, weight, sec_id) values (647, 'test', 0.9, 318);
insert into type (t_id, type, weight, sec_id) values (648, 'test', 0.3, 196);
insert into type (t_id, type, weight, sec_id) values (649, 'test', 0.8, 242);
insert into type (t_id, type, weight, sec_id) values (650, 'homework', 0.6, 269);
insert into type (t_id, type, weight, sec_id) values (651, 'project', 0.5, 198);
insert into type (t_id, type, weight, sec_id) values (652, 'test', 0.7, 84);
insert into type (t_id, type, weight, sec_id) values (653, 'homework', 0.7, 607);
insert into type (t_id, type, weight, sec_id) values (654, 'extra credit', 0.9, 224);
insert into type (t_id, type, weight, sec_id) values (655, 'homework', 0.7, 105);
insert into type (t_id, type, weight, sec_id) values (656, 'extra credit', 0.1, 423);
insert into type (t_id, type, weight, sec_id) values (657, 'test', 0.7, 168);
insert into type (t_id, type, weight, sec_id) values (658, 'homework', 0.3, 499);
insert into type (t_id, type, weight, sec_id) values (659, 'homework', 0.6, 23);
insert into type (t_id, type, weight, sec_id) values (660, 'extra credit', 0.6, 217);
insert into type (t_id, type, weight, sec_id) values (661, 'homework', 0.6, 74);
insert into type (t_id, type, weight, sec_id) values (662, 'project', 0.8, 219);
insert into type (t_id, type, weight, sec_id) values (663, 'homework', 0.7, 228);
insert into type (t_id, type, weight, sec_id) values (664, 'test', 0.3, 78);
insert into type (t_id, type, weight, sec_id) values (665, 'homework', 0.0, 14);
insert into type (t_id, type, weight, sec_id) values (666, 'test', 0.8, 331);
insert into type (t_id, type, weight, sec_id) values (667, 'extra credit', 0.4, 507);
insert into type (t_id, type, weight, sec_id) values (668, 'test', 0.6, 608);
insert into type (t_id, type, weight, sec_id) values (669, 'project', 0.3, 2);
insert into type (t_id, type, weight, sec_id) values (670, 'homework', 0.9, 29);
insert into type (t_id, type, weight, sec_id) values (671, 'extra credit', 0.3, 281);
insert into type (t_id, type, weight, sec_id) values (672, 'extra credit', 0.7, 477);
insert into type (t_id, type, weight, sec_id) values (673, 'project', 0.8, 436);
insert into type (t_id, type, weight, sec_id) values (674, 'homework', 0.0, 14);
insert into type (t_id, type, weight, sec_id) values (675, 'project', 0.6, 662);
insert into type (t_id, type, weight, sec_id) values (676, 'project', 0.5, 384);
insert into type (t_id, type, weight, sec_id) values (677, 'test', 0.5, 146);
insert into type (t_id, type, weight, sec_id) values (678, 'project', 0.1, 891);
insert into type (t_id, type, weight, sec_id) values (679, 'extra credit', 0.1, 420);
insert into type (t_id, type, weight, sec_id) values (680, 'extra credit', 0.2, 905);
insert into type (t_id, type, weight, sec_id) values (681, 'project', 0.6, 370);
insert into type (t_id, type, weight, sec_id) values (682, 'project', 0.5, 599);
insert into type (t_id, type, weight, sec_id) values (683, 'extra credit', 0.7, 149);
insert into type (t_id, type, weight, sec_id) values (684, 'homework', 0.5, 602);
insert into type (t_id, type, weight, sec_id) values (685, 'test', 0.2, 409);
insert into type (t_id, type, weight, sec_id) values (686, 'homework', 0.3, 261);
insert into type (t_id, type, weight, sec_id) values (687, 'project', 0.1, 901);
insert into type (t_id, type, weight, sec_id) values (688, 'test', 0.1, 939);
insert into type (t_id, type, weight, sec_id) values (689, 'homework', 0.9, 827);
insert into type (t_id, type, weight, sec_id) values (690, 'homework', 1.0, 189);
insert into type (t_id, type, weight, sec_id) values (691, 'homework', 0.3, 818);
insert into type (t_id, type, weight, sec_id) values (692, 'test', 0.8, 720);
insert into type (t_id, type, weight, sec_id) values (693, 'homework', 0.1, 973);
insert into type (t_id, type, weight, sec_id) values (694, 'homework', 0.9, 772);
insert into type (t_id, type, weight, sec_id) values (695, 'homework', 0.3, 365);
insert into type (t_id, type, weight, sec_id) values (696, 'extra credit', 0.6, 368);
insert into type (t_id, type, weight, sec_id) values (697, 'project', 0.6, 941);
insert into type (t_id, type, weight, sec_id) values (698, 'extra credit', 0.8, 143);
insert into type (t_id, type, weight, sec_id) values (699, 'extra credit', 0.3, 261);
insert into type (t_id, type, weight, sec_id) values (700, 'project', 0.3, 621);
insert into type (t_id, type, weight, sec_id) values (701, 'test', 0.0, 784);
insert into type (t_id, type, weight, sec_id) values (702, 'extra credit', 0.4, 907);
insert into type (t_id, type, weight, sec_id) values (703, 'test', 0.9, 761);
insert into type (t_id, type, weight, sec_id) values (704, 'homework', 0.7, 671);
insert into type (t_id, type, weight, sec_id) values (705, 'project', 1.0, 817);
insert into type (t_id, type, weight, sec_id) values (706, 'homework', 0.2, 423);
insert into type (t_id, type, weight, sec_id) values (707, 'homework', 0.6, 572);
insert into type (t_id, type, weight, sec_id) values (708, 'project', 1.0, 41);
insert into type (t_id, type, weight, sec_id) values (709, 'homework', 0.4, 582);
insert into type (t_id, type, weight, sec_id) values (710, 'project', 0.4, 952);
insert into type (t_id, type, weight, sec_id) values (711, 'project', 0.8, 248);
insert into type (t_id, type, weight, sec_id) values (712, 'extra credit', 1.0, 432);
insert into type (t_id, type, weight, sec_id) values (713, 'extra credit', 0.0, 872);
insert into type (t_id, type, weight, sec_id) values (714, 'test', 0.9, 976);
insert into type (t_id, type, weight, sec_id) values (715, 'project', 0.2, 531);
insert into type (t_id, type, weight, sec_id) values (716, 'extra credit', 0.6, 802);
insert into type (t_id, type, weight, sec_id) values (717, 'homework', 1.0, 723);
insert into type (t_id, type, weight, sec_id) values (718, 'test', 0.1, 331);
insert into type (t_id, type, weight, sec_id) values (719, 'extra credit', 0.2, 743);
insert into type (t_id, type, weight, sec_id) values (720, 'project', 0.4, 607);
insert into type (t_id, type, weight, sec_id) values (721, 'homework', 0.8, 898);
insert into type (t_id, type, weight, sec_id) values (722, 'test', 0.1, 558);
insert into type (t_id, type, weight, sec_id) values (723, 'extra credit', 0.9, 790);
insert into type (t_id, type, weight, sec_id) values (724, 'project', 1.0, 782);
insert into type (t_id, type, weight, sec_id) values (725, 'homework', 0.4, 521);
insert into type (t_id, type, weight, sec_id) values (726, 'extra credit', 0.2, 769);
insert into type (t_id, type, weight, sec_id) values (727, 'project', 0.8, 546);
insert into type (t_id, type, weight, sec_id) values (728, 'homework', 1.0, 110);
insert into type (t_id, type, weight, sec_id) values (729, 'project', 0.1, 340);
insert into type (t_id, type, weight, sec_id) values (730, 'project', 0.0, 89);
insert into type (t_id, type, weight, sec_id) values (731, 'extra credit', 0.5, 848);
insert into type (t_id, type, weight, sec_id) values (732, 'project', 0.4, 447);
insert into type (t_id, type, weight, sec_id) values (733, 'homework', 0.3, 362);
insert into type (t_id, type, weight, sec_id) values (734, 'test', 0.7, 905);
insert into type (t_id, type, weight, sec_id) values (735, 'extra credit', 0.5, 396);
insert into type (t_id, type, weight, sec_id) values (736, 'test', 1.0, 268);
insert into type (t_id, type, weight, sec_id) values (737, 'test', 0.1, 239);
insert into type (t_id, type, weight, sec_id) values (738, 'homework', 0.3, 377);
insert into type (t_id, type, weight, sec_id) values (739, 'project', 0.3, 206);
insert into type (t_id, type, weight, sec_id) values (740, 'project', 0.5, 90);
insert into type (t_id, type, weight, sec_id) values (741, 'homework', 0.2, 96);
insert into type (t_id, type, weight, sec_id) values (742, 'project', 0.4, 565);
insert into type (t_id, type, weight, sec_id) values (743, 'homework', 0.2, 921);
insert into type (t_id, type, weight, sec_id) values (744, 'test', 0.3, 470);
insert into type (t_id, type, weight, sec_id) values (745, 'homework', 0.2, 685);
insert into type (t_id, type, weight, sec_id) values (746, 'project', 0.9, 346);
insert into type (t_id, type, weight, sec_id) values (747, 'extra credit', 0.9, 363);
insert into type (t_id, type, weight, sec_id) values (748, 'project', 0.2, 403);
insert into type (t_id, type, weight, sec_id) values (749, 'homework', 0.3, 26);
insert into type (t_id, type, weight, sec_id) values (750, 'homework', 0.8, 210);
insert into type (t_id, type, weight, sec_id) values (751, 'homework', 1.0, 353);
insert into type (t_id, type, weight, sec_id) values (752, 'extra credit', 0.2, 482);
insert into type (t_id, type, weight, sec_id) values (753, 'homework', 0.4, 415);
insert into type (t_id, type, weight, sec_id) values (754, 'extra credit', 0.4, 738);
insert into type (t_id, type, weight, sec_id) values (755, 'extra credit', 0.1, 917);
insert into type (t_id, type, weight, sec_id) values (756, 'project', 0.2, 284);
insert into type (t_id, type, weight, sec_id) values (757, 'extra credit', 0.8, 506);
insert into type (t_id, type, weight, sec_id) values (758, 'homework', 0.7, 86);
insert into type (t_id, type, weight, sec_id) values (759, 'extra credit', 0.4, 358);
insert into type (t_id, type, weight, sec_id) values (760, 'homework', 1.0, 268);
insert into type (t_id, type, weight, sec_id) values (761, 'test', 0.6, 81);
insert into type (t_id, type, weight, sec_id) values (762, 'extra credit', 0.0, 102);
insert into type (t_id, type, weight, sec_id) values (763, 'homework', 0.7, 262);
insert into type (t_id, type, weight, sec_id) values (764, 'test', 0.4, 192);
insert into type (t_id, type, weight, sec_id) values (765, 'project', 0.2, 81);
insert into type (t_id, type, weight, sec_id) values (766, 'test', 0.9, 488);
insert into type (t_id, type, weight, sec_id) values (767, 'homework', 0.6, 719);
insert into type (t_id, type, weight, sec_id) values (768, 'homework', 0.3, 424);
insert into type (t_id, type, weight, sec_id) values (769, 'project', 0.2, 805);
insert into type (t_id, type, weight, sec_id) values (770, 'homework', 0.3, 185);
insert into type (t_id, type, weight, sec_id) values (771, 'project', 1.0, 703);
insert into type (t_id, type, weight, sec_id) values (772, 'homework', 0.3, 820);
insert into type (t_id, type, weight, sec_id) values (773, 'test', 0.9, 439);
insert into type (t_id, type, weight, sec_id) values (774, 'project', 0.3, 845);
insert into type (t_id, type, weight, sec_id) values (775, 'test', 0.8, 671);
insert into type (t_id, type, weight, sec_id) values (776, 'extra credit', 0.1, 223);
insert into type (t_id, type, weight, sec_id) values (777, 'homework', 0.6, 223);
insert into type (t_id, type, weight, sec_id) values (778, 'test', 0.6, 165);
insert into type (t_id, type, weight, sec_id) values (779, 'homework', 0.9, 66);
insert into type (t_id, type, weight, sec_id) values (780, 'homework', 0.1, 359);
insert into type (t_id, type, weight, sec_id) values (781, 'test', 0.2, 107);
insert into type (t_id, type, weight, sec_id) values (782, 'project', 1.0, 684);
insert into type (t_id, type, weight, sec_id) values (783, 'project', 0.6, 323);
insert into type (t_id, type, weight, sec_id) values (784, 'homework', 0.2, 645);
insert into type (t_id, type, weight, sec_id) values (785, 'homework', 0.9, 501);
insert into type (t_id, type, weight, sec_id) values (786, 'project', 1.0, 734);
insert into type (t_id, type, weight, sec_id) values (787, 'project', 0.7, 563);
insert into type (t_id, type, weight, sec_id) values (788, 'extra credit', 0.4, 987);
insert into type (t_id, type, weight, sec_id) values (789, 'extra credit', 0.1, 202);
insert into type (t_id, type, weight, sec_id) values (790, 'project', 0.4, 511);
insert into type (t_id, type, weight, sec_id) values (791, 'homework', 0.3, 52);
insert into type (t_id, type, weight, sec_id) values (792, 'extra credit', 0.5, 174);
insert into type (t_id, type, weight, sec_id) values (793, 'project', 0.1, 256);
insert into type (t_id, type, weight, sec_id) values (794, 'project', 0.1, 239);
insert into type (t_id, type, weight, sec_id) values (795, 'project', 0.2, 550);
insert into type (t_id, type, weight, sec_id) values (796, 'test', 0.3, 255);
insert into type (t_id, type, weight, sec_id) values (797, 'extra credit', 0.3, 318);
insert into type (t_id, type, weight, sec_id) values (798, 'homework', 0.1, 305);
insert into type (t_id, type, weight, sec_id) values (799, 'homework', 0.3, 942);
insert into type (t_id, type, weight, sec_id) values (800, 'test', 0.2, 775);
insert into type (t_id, type, weight, sec_id) values (801, 'extra credit', 0.7, 126);
insert into type (t_id, type, weight, sec_id) values (802, 'homework', 0.7, 371);
insert into type (t_id, type, weight, sec_id) values (803, 'extra credit', 0.0, 421);
insert into type (t_id, type, weight, sec_id) values (804, 'extra credit', 0.1, 922);
insert into type (t_id, type, weight, sec_id) values (805, 'project', 0.3, 700);
insert into type (t_id, type, weight, sec_id) values (806, 'extra credit', 0.6, 897);
insert into type (t_id, type, weight, sec_id) values (807, 'project', 0.3, 424);
insert into type (t_id, type, weight, sec_id) values (808, 'homework', 0.7, 686);
insert into type (t_id, type, weight, sec_id) values (809, 'test', 0.2, 775);
insert into type (t_id, type, weight, sec_id) values (810, 'project', 0.1, 884);
insert into type (t_id, type, weight, sec_id) values (811, 'project', 0.4, 498);
insert into type (t_id, type, weight, sec_id) values (812, 'project', 0.4, 265);
insert into type (t_id, type, weight, sec_id) values (813, 'project', 0.6, 923);
insert into type (t_id, type, weight, sec_id) values (814, 'homework', 0.5, 150);
insert into type (t_id, type, weight, sec_id) values (815, 'extra credit', 0.2, 743);
insert into type (t_id, type, weight, sec_id) values (816, 'homework', 0.8, 392);
insert into type (t_id, type, weight, sec_id) values (817, 'extra credit', 0.5, 369);
insert into type (t_id, type, weight, sec_id) values (818, 'homework', 0.6, 888);
insert into type (t_id, type, weight, sec_id) values (819, 'test', 0.0, 864);
insert into type (t_id, type, weight, sec_id) values (820, 'project', 0.4, 929);
insert into type (t_id, type, weight, sec_id) values (821, 'homework', 0.4, 999);
insert into type (t_id, type, weight, sec_id) values (822, 'project', 0.3, 487);
insert into type (t_id, type, weight, sec_id) values (823, 'project', 0.6, 771);
insert into type (t_id, type, weight, sec_id) values (824, 'test', 0.7, 830);
insert into type (t_id, type, weight, sec_id) values (825, 'project', 0.3, 731);
insert into type (t_id, type, weight, sec_id) values (826, 'test', 0.4, 623);
insert into type (t_id, type, weight, sec_id) values (827, 'test', 0.7, 86);
insert into type (t_id, type, weight, sec_id) values (828, 'extra credit', 0.4, 843);
insert into type (t_id, type, weight, sec_id) values (829, 'homework', 0.9, 751);
insert into type (t_id, type, weight, sec_id) values (830, 'test', 0.7, 629);
insert into type (t_id, type, weight, sec_id) values (831, 'extra credit', 0.4, 696);
insert into type (t_id, type, weight, sec_id) values (832, 'extra credit', 0.4, 833);
insert into type (t_id, type, weight, sec_id) values (833, 'homework', 0.4, 339);
insert into type (t_id, type, weight, sec_id) values (834, 'homework', 0.6, 155);
insert into type (t_id, type, weight, sec_id) values (835, 'test', 0.8, 516);
insert into type (t_id, type, weight, sec_id) values (836, 'homework', 0.6, 578);
insert into type (t_id, type, weight, sec_id) values (837, 'extra credit', 0.3, 454);
insert into type (t_id, type, weight, sec_id) values (838, 'project', 0.5, 694);
insert into type (t_id, type, weight, sec_id) values (839, 'project', 0.2, 371);
insert into type (t_id, type, weight, sec_id) values (840, 'project', 0.5, 802);
insert into type (t_id, type, weight, sec_id) values (841, 'project', 0.8, 341);
insert into type (t_id, type, weight, sec_id) values (842, 'homework', 0.3, 663);
insert into type (t_id, type, weight, sec_id) values (843, 'homework', 0.9, 914);
insert into type (t_id, type, weight, sec_id) values (844, 'homework', 0.7, 239);
insert into type (t_id, type, weight, sec_id) values (845, 'extra credit', 0.9, 289);
insert into type (t_id, type, weight, sec_id) values (846, 'project', 0.6, 158);
insert into type (t_id, type, weight, sec_id) values (847, 'project', 0.9, 546);
insert into type (t_id, type, weight, sec_id) values (848, 'homework', 0.9, 641);
insert into type (t_id, type, weight, sec_id) values (849, 'test', 0.1, 543);
insert into type (t_id, type, weight, sec_id) values (850, 'homework', 0.6, 78);
insert into type (t_id, type, weight, sec_id) values (851, 'project', 0.6, 693);
insert into type (t_id, type, weight, sec_id) values (852, 'project', 0.3, 395);
insert into type (t_id, type, weight, sec_id) values (853, 'homework', 0.3, 847);
insert into type (t_id, type, weight, sec_id) values (854, 'homework', 0.2, 675);
insert into type (t_id, type, weight, sec_id) values (855, 'test', 0.5, 750);
insert into type (t_id, type, weight, sec_id) values (856, 'test', 0.8, 807);
insert into type (t_id, type, weight, sec_id) values (857, 'project', 0.9, 882);
insert into type (t_id, type, weight, sec_id) values (858, 'extra credit', 0.3, 657);
insert into type (t_id, type, weight, sec_id) values (859, 'extra credit', 0.7, 349);
insert into type (t_id, type, weight, sec_id) values (860, 'test', 0.2, 749);
insert into type (t_id, type, weight, sec_id) values (861, 'extra credit', 1.0, 323);
insert into type (t_id, type, weight, sec_id) values (862, 'test', 0.4, 12);
insert into type (t_id, type, weight, sec_id) values (863, 'extra credit', 1.0, 152);
insert into type (t_id, type, weight, sec_id) values (864, 'project', 0.1, 966);
insert into type (t_id, type, weight, sec_id) values (865, 'test', 0.6, 480);
insert into type (t_id, type, weight, sec_id) values (866, 'test', 0.7, 712);
insert into type (t_id, type, weight, sec_id) values (867, 'project', 0.5, 144);
insert into type (t_id, type, weight, sec_id) values (868, 'extra credit', 0.4, 892);
insert into type (t_id, type, weight, sec_id) values (869, 'project', 0.9, 235);
insert into type (t_id, type, weight, sec_id) values (870, 'homework', 0.3, 520);
insert into type (t_id, type, weight, sec_id) values (871, 'test', 0.9, 93);
insert into type (t_id, type, weight, sec_id) values (872, 'homework', 0.8, 136);
insert into type (t_id, type, weight, sec_id) values (873, 'extra credit', 0.2, 68);
insert into type (t_id, type, weight, sec_id) values (874, 'homework', 0.6, 680);
insert into type (t_id, type, weight, sec_id) values (875, 'homework', 1.0, 191);
insert into type (t_id, type, weight, sec_id) values (876, 'test', 0.3, 985);
insert into type (t_id, type, weight, sec_id) values (877, 'homework', 0.7, 848);
insert into type (t_id, type, weight, sec_id) values (878, 'homework', 0.5, 474);
insert into type (t_id, type, weight, sec_id) values (879, 'project', 0.4, 357);
insert into type (t_id, type, weight, sec_id) values (880, 'extra credit', 0.4, 305);
insert into type (t_id, type, weight, sec_id) values (881, 'homework', 0.6, 138);
insert into type (t_id, type, weight, sec_id) values (882, 'extra credit', 0.9, 810);
insert into type (t_id, type, weight, sec_id) values (883, 'homework', 0.3, 323);
insert into type (t_id, type, weight, sec_id) values (884, 'extra credit', 0.5, 489);
insert into type (t_id, type, weight, sec_id) values (885, 'project', 0.2, 394);
insert into type (t_id, type, weight, sec_id) values (886, 'homework', 0.2, 123);
insert into type (t_id, type, weight, sec_id) values (887, 'test', 0.3, 839);
insert into type (t_id, type, weight, sec_id) values (888, 'project', 0.4, 4);
insert into type (t_id, type, weight, sec_id) values (889, 'homework', 0.4, 953);
insert into type (t_id, type, weight, sec_id) values (890, 'homework', 0.3, 593);
insert into type (t_id, type, weight, sec_id) values (891, 'homework', 0.0, 959);
insert into type (t_id, type, weight, sec_id) values (892, 'project', 0.3, 353);
insert into type (t_id, type, weight, sec_id) values (893, 'homework', 0.5, 399);
insert into type (t_id, type, weight, sec_id) values (894, 'project', 0.6, 505);
insert into type (t_id, type, weight, sec_id) values (895, 'homework', 0.3, 91);
insert into type (t_id, type, weight, sec_id) values (896, 'homework', 0.2, 817);
insert into type (t_id, type, weight, sec_id) values (897, 'project', 0.7, 517);
insert into type (t_id, type, weight, sec_id) values (898, 'homework', 1.0, 195);
insert into type (t_id, type, weight, sec_id) values (899, 'homework', 0.5, 20);
insert into type (t_id, type, weight, sec_id) values (900, 'extra credit', 0.1, 93);
insert into type (t_id, type, weight, sec_id) values (901, 'test', 0.9, 919);
insert into type (t_id, type, weight, sec_id) values (902, 'project', 0.4, 58);
insert into type (t_id, type, weight, sec_id) values (903, 'test', 0.9, 600);
insert into type (t_id, type, weight, sec_id) values (904, 'homework', 0.4, 23);
insert into type (t_id, type, weight, sec_id) values (905, 'homework', 0.1, 807);
insert into type (t_id, type, weight, sec_id) values (906, 'homework', 0.0, 22);
insert into type (t_id, type, weight, sec_id) values (907, 'project', 0.3, 982);
insert into type (t_id, type, weight, sec_id) values (908, 'test', 0.9, 285);
insert into type (t_id, type, weight, sec_id) values (909, 'test', 0.5, 563);
insert into type (t_id, type, weight, sec_id) values (910, 'test', 0.6, 156);
insert into type (t_id, type, weight, sec_id) values (911, 'test', 0.1, 191);
insert into type (t_id, type, weight, sec_id) values (912, 'test', 0.1, 805);
insert into type (t_id, type, weight, sec_id) values (913, 'project', 0.5, 817);
insert into type (t_id, type, weight, sec_id) values (914, 'homework', 0.4, 389);
insert into type (t_id, type, weight, sec_id) values (915, 'test', 0.6, 322);
insert into type (t_id, type, weight, sec_id) values (916, 'project', 0.8, 658);
insert into type (t_id, type, weight, sec_id) values (917, 'extra credit', 0.9, 551);
insert into type (t_id, type, weight, sec_id) values (918, 'project', 1.0, 345);
insert into type (t_id, type, weight, sec_id) values (919, 'extra credit', 0.8, 388);
insert into type (t_id, type, weight, sec_id) values (920, 'test', 0.4, 309);
insert into type (t_id, type, weight, sec_id) values (921, 'extra credit', 0.1, 488);
insert into type (t_id, type, weight, sec_id) values (922, 'extra credit', 0.6, 50);
insert into type (t_id, type, weight, sec_id) values (923, 'test', 0.7, 98);
insert into type (t_id, type, weight, sec_id) values (924, 'homework', 1.0, 14);
insert into type (t_id, type, weight, sec_id) values (925, 'test', 0.9, 856);
insert into type (t_id, type, weight, sec_id) values (926, 'extra credit', 0.5, 863);
insert into type (t_id, type, weight, sec_id) values (927, 'homework', 0.9, 972);
insert into type (t_id, type, weight, sec_id) values (928, 'homework', 0.5, 609);
insert into type (t_id, type, weight, sec_id) values (929, 'project', 0.5, 983);
insert into type (t_id, type, weight, sec_id) values (930, 'homework', 0.3, 359);
insert into type (t_id, type, weight, sec_id) values (931, 'homework', 0.1, 577);
insert into type (t_id, type, weight, sec_id) values (932, 'project', 0.5, 857);
insert into type (t_id, type, weight, sec_id) values (933, 'extra credit', 0.1, 385);
insert into type (t_id, type, weight, sec_id) values (934, 'project', 0.0, 855);
insert into type (t_id, type, weight, sec_id) values (935, 'project', 0.7, 21);
insert into type (t_id, type, weight, sec_id) values (936, 'test', 0.0, 854);
insert into type (t_id, type, weight, sec_id) values (937, 'project', 0.2, 182);
insert into type (t_id, type, weight, sec_id) values (938, 'test', 0.1, 414);
insert into type (t_id, type, weight, sec_id) values (939, 'project', 0.8, 40);
insert into type (t_id, type, weight, sec_id) values (940, 'homework', 0.3, 531);
insert into type (t_id, type, weight, sec_id) values (941, 'extra credit', 0.7, 135);
insert into type (t_id, type, weight, sec_id) values (942, 'homework', 0.8, 758);
insert into type (t_id, type, weight, sec_id) values (943, 'test', 0.3, 97);
insert into type (t_id, type, weight, sec_id) values (944, 'project', 0.3, 645);
insert into type (t_id, type, weight, sec_id) values (945, 'test', 0.4, 781);
insert into type (t_id, type, weight, sec_id) values (946, 'test', 0.6, 457);
insert into type (t_id, type, weight, sec_id) values (947, 'project', 0.0, 424);
insert into type (t_id, type, weight, sec_id) values (948, 'test', 0.4, 999);
insert into type (t_id, type, weight, sec_id) values (949, 'homework', 0.9, 168);
insert into type (t_id, type, weight, sec_id) values (950, 'test', 0.5, 701);
insert into type (t_id, type, weight, sec_id) values (951, 'project', 0.7, 403);
insert into type (t_id, type, weight, sec_id) values (952, 'test', 0.8, 952);
insert into type (t_id, type, weight, sec_id) values (953, 'test', 0.3, 266);
insert into type (t_id, type, weight, sec_id) values (954, 'homework', 0.7, 77);
insert into type (t_id, type, weight, sec_id) values (955, 'test', 0.1, 534);
insert into type (t_id, type, weight, sec_id) values (956, 'test', 0.6, 554);
insert into type (t_id, type, weight, sec_id) values (957, 'project', 0.6, 770);
insert into type (t_id, type, weight, sec_id) values (958, 'homework', 0.2, 838);
insert into type (t_id, type, weight, sec_id) values (959, 'test', 0.7, 847);
insert into type (t_id, type, weight, sec_id) values (960, 'test', 0.8, 752);
insert into type (t_id, type, weight, sec_id) values (961, 'test', 0.1, 660);
insert into type (t_id, type, weight, sec_id) values (962, 'project', 0.1, 611);
insert into type (t_id, type, weight, sec_id) values (963, 'extra credit', 0.5, 246);
insert into type (t_id, type, weight, sec_id) values (964, 'project', 1.0, 836);
insert into type (t_id, type, weight, sec_id) values (965, 'project', 0.9, 236);
insert into type (t_id, type, weight, sec_id) values (966, 'homework', 0.5, 605);
insert into type (t_id, type, weight, sec_id) values (967, 'test', 0.1, 462);
insert into type (t_id, type, weight, sec_id) values (968, 'homework', 0.1, 578);
insert into type (t_id, type, weight, sec_id) values (969, 'project', 0.9, 410);
insert into type (t_id, type, weight, sec_id) values (970, 'extra credit', 0.1, 991);
insert into type (t_id, type, weight, sec_id) values (971, 'homework', 0.8, 648);
insert into type (t_id, type, weight, sec_id) values (972, 'test', 0.4, 714);
insert into type (t_id, type, weight, sec_id) values (973, 'extra credit', 0.5, 617);
insert into type (t_id, type, weight, sec_id) values (974, 'homework', 0.3, 531);
insert into type (t_id, type, weight, sec_id) values (975, 'project', 1.0, 190);
insert into type (t_id, type, weight, sec_id) values (976, 'extra credit', 0.7, 248);
insert into type (t_id, type, weight, sec_id) values (977, 'test', 0.4, 531);
insert into type (t_id, type, weight, sec_id) values (978, 'extra credit', 0.1, 769);
insert into type (t_id, type, weight, sec_id) values (979, 'extra credit', 0.8, 272);
insert into type (t_id, type, weight, sec_id) values (980, 'extra credit', 0.3, 546);
insert into type (t_id, type, weight, sec_id) values (981, 'extra credit', 0.2, 780);
insert into type (t_id, type, weight, sec_id) values (982, 'project', 0.4, 228);
insert into type (t_id, type, weight, sec_id) values (983, 'extra credit', 0.3, 875);
insert into type (t_id, type, weight, sec_id) values (984, 'extra credit', 0.9, 769);
insert into type (t_id, type, weight, sec_id) values (985, 'homework', 0.3, 625);
insert into type (t_id, type, weight, sec_id) values (986, 'extra credit', 0.7, 302);
insert into type (t_id, type, weight, sec_id) values (987, 'homework', 0.3, 747);
insert into type (t_id, type, weight, sec_id) values (988, 'homework', 0.2, 51);
insert into type (t_id, type, weight, sec_id) values (989, 'extra credit', 0.9, 234);
insert into type (t_id, type, weight, sec_id) values (990, 'homework', 0.6, 391);
insert into type (t_id, type, weight, sec_id) values (991, 'extra credit', 0.7, 649);
insert into type (t_id, type, weight, sec_id) values (992, 'test', 0.7, 981);
insert into type (t_id, type, weight, sec_id) values (993, 'test', 0.5, 83);
insert into type (t_id, type, weight, sec_id) values (994, 'test', 0.0, 802);
insert into type (t_id, type, weight, sec_id) values (995, 'project', 0.6, 579);
insert into type (t_id, type, weight, sec_id) values (996, 'homework', 0.8, 787);
insert into type (t_id, type, weight, sec_id) values (997, 'extra credit', 0.3, 816);
insert into type (t_id, type, weight, sec_id) values (998, 'extra credit', 0.2, 922);
insert into type (t_id, type, weight, sec_id) values (999, 'extra credit', 0.0, 368);
insert into type (t_id, type, weight, sec_id) values (1000, 'homework', 0.4, 913);
